feat: add workflows for version management and tagging (#348)
* add: initial files for `release-new-version`

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug(release-new-version): fix invalid format yaml

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug: fix by applying pre-commit

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug: fix missing "shell" property

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug: one more missing "shell" property, ... (sorry)

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug: fix incorrect command

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug: fix following error

```
/home/runner/work/_temp/a9d77c78-327e-43c5-bdcf-dd091882b13d.sh: line 7: CHANGELOG.rst: command not found
[bump/main-to-humble-with-patch-15321664969 4cdb6da] chore: update all s
```

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug: fix following error by non-interactive mode

```
Found packages: dummy_package
Traceback (most recent call last):
  File "/home/runner/.local/bin/catkin_prepare_release", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/lib/python3.10/site-packages/catkin_pkg/cli/prepare_release.py", line 217, in main
    _main()
  File "/home/runner/.local/lib/python3.10/site-packages/catkin_pkg/cli/prepare_release.py", line 323, in _main
    not prompt_continue(
  File "/home/runner/.local/lib/python3.10/site-packages/catkin_pkg/cli/prepare_release.py", line 52, in prompt_continue
    _flush_stdin()
  File "/home/runner/.local/lib/python3.10/site-packages/catkin_pkg/cli/prepare_release.py", line 75, in _flush_stdin
    tcflush(sys.stdin, TCIFLUSH)
termios.error: (25, 'Inappropriate ioctl for device')
```

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug: do not use unnecessary flag

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug: remove duplicated `git commit`

  * This causes following error:
```
nothing to commit, working tree clean
```

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* rename: `release-new-version` => `bump-new-version`

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* add: initial files for `release-new-tag-when-merged`

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug: fix syntax error

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug(release-new-tag-when-merged): fix to be run-able

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* style(pre-commit): autofix

* bug: fix by pre-commit

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug: fixes as follows

  * Fix inconsistent naming
  * Fix confusing comment
  * Remove unused comment
  * Remove unused id

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug(release-new-version): fix inconsistent naming

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug: remove unused id and fix comment

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* fix(bump-new-version): avoid error exit if no change exists

  * `catkin_generate_changelog --all` outputs the following error
    when no change exists
```
ERROR: All packages already have a changelog. Either remove (some of) them before using --all or invoke the script without --all.
```

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug: fix errors such as following ones

  * Idempotency bugs
  * Version mismatch cannot be handled
  * Wrong/missing descriptions
  * ... etc

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* style(pre-commit): autofix

* bug(bump-new-version): fix wrong version before CHANGELOG.rst creation

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug(README.md): fix missing properties

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug(bump-new-version): fix missing update for already existing packages

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* bug(bump-new-version): fix a bug when the first bump

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

* Update bump-new-version/README.md

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>

Co-authored-by: Yutaka Kondo <yutaka.kondo@youtalk.jp>

* style(pre-commit): autofix

---------

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: Yutaka Kondo <yutaka.kondo@youtalk.jp>